// export const countries = [
//   { value: "afghanistan", label: "Afghanistan" },
//   { value: "afrique-du-sud", label: "Afrique du Sud" },
//   { value: "albanie", label: "Albanie" },
//   { value: "algerie", label: "Algérie" },
//   { value: "allemagne", label: "Allemagne" },
//   { value: "andorre", label: "Andorre" },
//   { value: "angola", label: "Angola" },
//   { value: "antigua-et-barbuda", label: "Antigua-et-Barbuda" },
//   { value: "arabie-saoudite", label: "Arabie saoudite" },
//   { value: "argentine", label: "Argentine" },
//   { value: "armenie", label: "Arménie" },
//   { value: "australie", label: "Australie" },
//   { value: "autriche", label: "Autriche" },
//   { value: "azerbaidjan", label: "Azerbaïdjan" },
//   { value: "bahamas", label: "Bahamas" },
//   { value: "bahrein", label: "Bahreïn" },
//   { value: "bangladesh", label: "Bangladesh" },
//   { value: "barbade", label: "Barbade" },
//   { value: "belgique", label: "Belgique" },
//   { value: "belize", label: "Belize" },
//   { value: "benin", label: "Bénin" },
//   { value: "bhoutan", label: "Bhoutan" },
//   { value: "bielorussie", label: "Biélorussie" },
//   { value: "birmanie", label: "Birmanie" },
//   { value: "bolivie", label: "Bolivie" },
//   { value: "bosnie-herzegovine", label: "Bosnie-Herzégovine" },
//   { value: "botswana", label: "Botswana" },
//   { value: "bresil", label: "Brésil" },
//   { value: "brunei", label: "Brunei" },
//   { value: "bulgarie", label: "Bulgarie" },
//   { value: "burkina-faso", label: "Burkina Faso" },
//   { value: "burundi", label: "Burundi" },
//   { value: "cambodge", label: "Cambodge" },
//   { value: "cameroun", label: "Cameroun" },
//   { value: "canada", label: "Canada" },
//   { value: "cap-vert", label: "Cap-Vert" },
//   { value: "centrafrique", label: "Centrafrique" },
//   { value: "chili", label: "Chili" },
//   { value: "chine", label: "Chine" },
//   { value: "chypre", label: "Chypre" },
//   { value: "colombie", label: "Colombie" },
//   { value: "comores", label: "Comores" },
//   { value: "congo", label: "Congo" },
//   { value: "congo-democratique", label: "Congo démocratique" },
//   { value: "coree-du-nord", label: "Corée du Nord" },
//   { value: "coree-du-sud", label: "Corée du Sud" },
//   { value: "costa-rica", label: "Costa Rica" },
//   { value: "cote-divoire", label: "Côte d'Ivoire" },
//   { value: "croatie", label: "Croatie" },
//   { value: "cuba", label: "Cuba" },
//   { value: "danemark", label: "Danemark" },
//   { value: "djibouti", label: "Djibouti" },
//   { value: "dominique", label: "Dominique" },
//   { value: "egypte", label: "Égypte" },
//   { value: "emirats-arabes-unis", label: "Émirats arabes unis" },
//   { value: "equateur", label: "Équateur" },
//   { value: "erythree", label: "Érythrée" },
//   { value: "espagne", label: "Espagne" },
//   { value: "estonie", label: "Estonie" },
//   { value: "etats-unis", label: "États-Unis" },
//   { value: "ethiopie", label: "Éthiopie" },
//   { value: "fidji", label: "Fidji" },
//   { value: "finlande", label: "Finlande" },
//   { value: "france", label: "France" },
//   { value: "gabon", label: "Gabon" },
//   { value: "gambie", label: "Gambie" },
//   { value: "georgie", label: "Géorgie" },
//   { value: "ghana", label: "Ghana" },
//   { value: "grece", label: "Grèce" },
//   { value: "grenade", label: "Grenade" },
//   { value: "guatemala", label: "Guatemala" },
//   { value: "guinee", label: "Guinée" },
//   { value: "guinee-bissau", label: "Guinée-Bissau" },
//   { value: "guinee-equatoriale", label: "Guinée équatoriale" },
//   { value: "guyana", label: "Guyana" },
//   { value: "haiti", label: "Haïti" },
//   { value: "honduras", label: "Honduras" },
//   { value: "hongrie", label: "Hongrie" },
//   { value: "inde", label: "Inde" },
//   { value: "indonesie", label: "Indonésie" },
//   { value: "irak", label: "Irak" },
//   { value: "iran", label: "Iran" },
//   { value: "irlande", label: "Irlande" },
//   { value: "islande", label: "Islande" },
//   { value: "israel", label: "Israël" },
//   { value: "italie", label: "Italie" },
//   { value: "jamaique", label: "Jamaïque" },
//   { value: "japon", label: "Japon" },
//   { value: "jordanie", label: "Jordanie" },
//   { value: "kazakhstan", label: "Kazakhstan" },
//   { value: "kenya", label: "Kenya" },
//   { value: "kirghizistan", label: "Kirghizistan" },
//   { value: "kiribati", label: "Kiribati" },
//   { value: "koweit", label: "Koweït" },
//   { value: "laos", label: "Laos" },
//   { value: "lesotho", label: "Lesotho" },
//   { value: "lettonie", label: "Lettonie" },
//   { value: "liban", label: "Liban" },
//   { value: "liberia", label: "Liberia" },
//   { value: "libye", label: "Libye" },
//   { value: "liechtenstein", label: "Liechtenstein" },
//   { value: "lituanie", label: "Lituanie" },
//   { value: "luxembourg", label: "Luxembourg" },
//   { value: "macedoine", label: "Macédoine" },
//   { value: "madagascar", label: "Madagascar" },
//   { value: "malaisie", label: "Malaisie" },
//   { value: "malawi", label: "Malawi" },
//   { value: "maldives", label: "Maldives" },
//   { value: "mali", label: "Mali" },
//   { value: "malte", label: "Malte" },
//   { value: "maroc", label: "Maroc" },
//   { value: "marshall", label: "Marshall" },
//   { value: "maurice", label: "Maurice" },
//   { value: "mauritanie", label: "Mauritanie" },
//   { value: "mexique", label: "Mexique" },
//   { value: "micronesie", label: "Micronésie" },
//   { value: "moldavie", label: "Moldavie" },
//   { value: "monaco", label: "Monaco" },
//   { value: "mongolie", label: "Mongolie" },
//   { value: "montenegro", label: "Monténégro" },
//   { value: "mozambique", label: "Mozambique" },
//   { value: "namibie", label: "Namibie" },
//   { value: "nauru", label: "Nauru" },
//   { value: "nepal", label: "Népal" },
//   { value: "nicaragua", label: "Nicaragua" },
//   { value: "niger", label: "Niger" },
//   { value: "nigeria", label: "Nigeria" },
//   { value: "norvege", label: "Norvège" },
//   { value: "nouvelle-zelande", label: "Nouvelle-Zélande" },
//   { value: "oman", label: "Oman" },
//   { value: "ouganda", label: "Ouganda" },
//   { value: "ouzbekistan", label: "Ouzbékistan" },
//   { value: "pakistan", label: "Pakistan" },
//   { value: "palaos", label: "Palaos" },
//   { value: "panama", label: "Panama" },
//   { value: "papouasie-nouvelle-guinee", label: "Papouasie-Nouvelle-Guinée" },
//   { value: "paraguay", label: "Paraguay" },
//   { value: "pays-bas", label: "Pays-Bas" },
//   { value: "perou", label: "Pérou" },
//   { value: "philippines", label: "Philippines" },
//   { value: "pologne", label: "Pologne" },
//   { value: "portugal", label: "Portugal" },
//   { value: "qatar", label: "Qatar" },
//   { value: "republique-dominicaine", label: "République dominicaine" },
//   { value: "republique-tcheque", label: "République tchèque" },
//   { value: "roumanie", label: "Roumanie" },
//   { value: "royaume-uni", label: "Royaume-Uni" },
//   { value: "russie", label: "Russie" },
//   { value: "rwanda", label: "Rwanda" },
//   { value: "saint-christophe-et-nieves", label: "Saint-Christophe-et-Niévès" },
//   { value: "saint-marin", label: "Saint-Marin" },
//   { value: "saint-vincent-et-les-grenadines", label: "Saint-Vincent-et-les-Grenadines" },
//   { value: "sainte-lucie", label: "Sainte-Lucie" },
//   { value: "salomon", label: "Salomon" },
//   { value: "salvador", label: "Salvador" },
//   { value: "samoa", label: "Samoa" },
//   { value: "sao-tome-et-principe", label: "Sao Tomé-et-Principe" },
//   { value: "senegal", label: "Sénégal" },
//   { value: "serbie", label: "Serbie" },
//   { value: "seychelles", label: "Seychelles" },
//   { value: "sierra-leone", label: "Sierra Leone" },
//   { value: "singapour", label: "Singapour" },
//   { value: "slovaquie", label: "Slovaquie" },
//   { value: "slovenie", label: "Slovénie" },
//   { value: "somalie", label: "Somalie" },
//   { value: "soudan", label: "Soudan" },
//   { value: "soudan-du-sud", label: "Soudan du Sud" },
//   { value: "sri-lanka", label: "Sri Lanka" },
//   { value: "suede", label: "Suède" },
//   { value: "suisse", label: "Suisse" },
//   { value: "suriname", label: "Suriname" },
//   { value: "swaziland", label: "Swaziland" },
//   { value: "syrie", label: "Syrie" },
//   { value: "tadjikistan", label: "Tadjikistan" },
//   { value: "tanzanie", label: "Tanzanie" },
//   { value: "tchad", label: "Tchad" },
//   { value: "thailande", label: "Thaïlande" },
//   { value: "timor-oriental", label: "Timor oriental" },
//   { value: "togo", label: "Togo" },
//   { value: "tonga", label: "Tonga" },
//   { value: "trinite-et-tobago", label: "Trinité-et-Tobago" },
//   { value: "tunisie", label: "Tunisie" },
//   { value: "turkmenistan", label: "Turkménistan" },
//   { value: "turquie", label: "Turquie" },
//   { value: "tuvalu", label: "Tuvalu" },
//   { value: "ukraine", label: "Ukraine" },
//   { value: "uruguay", label: "Uruguay" },
//   { value: "vanuatu", label: "Vanuatu" },
//   { value: "vatican", label: "Vatican" },
//   { value: "venezuela", label: "Venezuela" },
//   { value: "vietnam", label: "Viêt Nam" },
//   { value: "yemen", label: "Yémen" },
//   { value: "zambie", label: "Zambie" },
//   { value: "zimbabwe", label: "Zimbabwe" },
// ]
export const countries = [
  { value: "afghanistan", label: "Afghanistan", labelEn: "Afghanistan" },
  { value: "afrique-du-sud", label: "Afrique du Sud", labelEn: "South Africa" },
  { value: "albanie", label: "Albanie", labelEn: "Albania" },
  { value: "algerie", label: "Algérie", labelEn: "Algeria" },
  { value: "allemagne", label: "Allemagne", labelEn: "Germany" },
  { value: "andorre", label: "Andorre", labelEn: "Andorra" },
  { value: "angola", label: "Angola", labelEn: "Angola" },
  { value: "antigua-et-barbuda", label: "Antigua-et-Barbuda", labelEn: "Antigua and Barbuda" },
  { value: "arabie-saoudite", label: "Arabie saoudite", labelEn: "Saudi Arabia" },
  { value: "argentine", label: "Argentine", labelEn: "Argentina" },
  { value: "armenie", label: "Arménie", labelEn: "Armenia" },
  { value: "australie", label: "Australie", labelEn: "Australia" },
  { value: "autriche", label: "Autriche", labelEn: "Austria" },
  { value: "azerbaidjan", label: "Azerbaïdjan", labelEn: "Azerbaijan" },
  { value: "bahamas", label: "Bahamas", labelEn: "Bahamas" },
  { value: "bahrein", label: "Bahreïn", labelEn: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh", labelEn: "Bangladesh" },
  { value: "barbade", label: "Barbade", labelEn: "Barbados" },
  { value: "belgique", label: "Belgique", labelEn: "Belgium" },
  { value: "belize", label: "Belize", labelEn: "Belize" },
  { value: "benin", label: "Bénin", labelEn: "Benin" },
  { value: "bhoutan", label: "Bhoutan", labelEn: "Bhutan" },
  { value: "bielorussie", label: "Biélorussie", labelEn: "Belarus" },
  { value: "birmanie", label: "Birmanie", labelEn: "Myanmar" },
  { value: "bolivie", label: "Bolivie", labelEn: "Bolivia" },
  { value: "bosnie-herzegovine", label: "Bosnie-Herzégovine", labelEn: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana", labelEn: "Botswana" },
  { value: "bresil", label: "Brésil", labelEn: "Brazil" },
  { value: "brunei", label: "Brunei", labelEn: "Brunei" },
  { value: "bulgarie", label: "Bulgarie", labelEn: "Bulgaria" },
  { value: "burkina-faso", label: "Burkina Faso", labelEn: "Burkina Faso" },
  { value: "burundi", label: "Burundi", labelEn: "Burundi" },
  { value: "cambodge", label: "Cambodge", labelEn: "Cambodia" },
  { value: "cameroun", label: "Cameroun", labelEn: "Cameroon" },
  { value: "canada", label: "Canada", labelEn: "Canada" },
  { value: "cap-vert", label: "Cap-Vert", labelEn: "Cape Verde" },
  { value: "centrafrique", label: "Centrafrique", labelEn: "Central African Republic" },
  { value: "chili", label: "Chili", labelEn: "Chile" },
  { value: "chine", label: "Chine", labelEn: "China" },
  { value: "chypre", label: "Chypre", labelEn: "Cyprus" },
  { value: "colombie", label: "Colombie", labelEn: "Colombia" },
  { value: "comores", label: "Comores", labelEn: "Comoros" },
  { value: "congo", label: "Congo", labelEn: "Republic of the Congo" },
  { value: "congo-democratique", label: "Congo démocratique", labelEn: "Democratic Republic of the Congo" },
  { value: "coree-du-nord", label: "Corée du Nord", labelEn: "North Korea" },
  { value: "coree-du-sud", label: "Corée du Sud", labelEn: "South Korea" },
  { value: "costa-rica", label: "Costa Rica", labelEn: "Costa Rica" },
  { value: "cote-divoire", label: "Côte d'Ivoire", labelEn: "Ivory Coast" },
  { value: "croatie", label: "Croatie", labelEn: "Croatia" },
  { value: "cuba", label: "Cuba", labelEn: "Cuba" },
  { value: "danemark", label: "Danemark", labelEn: "Denmark" },
  { value: "djibouti", label: "Djibouti", labelEn: "Djibouti" },
  { value: "dominique", label: "Dominique", labelEn: "Dominica" },
  { value: "egypte", label: "Égypte", labelEn: "Egypt" },
  { value: "emirats-arabes-unis", label: "Émirats arabes unis", labelEn: "United Arab Emirates" },
  { value: "equateur", label: "Équateur", labelEn: "Ecuador" },
  { value: "erythree", label: "Érythrée", labelEn: "Eritrea" },
  { value: "espagne", label: "Espagne", labelEn: "Spain" },
  { value: "estonie", label: "Estonie", labelEn: "Estonia" },
  { value: "etats-unis", label: "États-Unis", labelEn: "United States" },
  { value: "ethiopie", label: "Éthiopie", labelEn: "Ethiopia" },
  { value: "fidji", label: "Fidji", labelEn: "Fiji" },
  { value: "finlande", label: "Finlande", labelEn: "Finland" },
  { value: "france", label: "France", labelEn: "France" },
  { value: "gabon", label: "Gabon", labelEn: "Gabon" },
  { value: "gambie", label: "Gambie", labelEn: "Gambia" },
  { value: "georgie", label: "Géorgie", labelEn: "Georgia" },
  { value: "ghana", label: "Ghana", labelEn: "Ghana" },
  { value: "grece", label: "Grèce", labelEn: "Greece" },
  { value: "grenade", label: "Grenade", labelEn: "Grenada" },
  { value: "guatemala", label: "Guatemala", labelEn: "Guatemala" },
  { value: "guinee", label: "Guinée", labelEn: "Guinea" },
  { value: "guinee-bissau", label: "Guinée-Bissau", labelEn: "Guinea-Bissau" },
  { value: "guinee-equatoriale", label: "Guinée équatoriale", labelEn: "Equatorial Guinea" },
  { value: "guyana", label: "Guyana", labelEn: "Guyana" },
  { value: "haiti", label: "Haïti", labelEn: "Haiti" },
  { value: "honduras", label: "Honduras", labelEn: "Honduras" },
  { value: "hongrie", label: "Hongrie", labelEn: "Hungary" },
  { value: "inde", label: "Inde", labelEn: "India" },
  { value: "indonesie", label: "Indonésie", labelEn: "Indonesia" },
  { value: "irak", label: "Irak", labelEn: "Iraq" },
  { value: "iran", label: "Iran", labelEn: "Iran" },
  { value: "irlande", label: "Irlande", labelEn: "Ireland" },
  { value: "islande", label: "Islande", labelEn: "Iceland" },
  { value: "israel", label: "Israël", labelEn: "Israel" },
  { value: "italie", label: "Italie", labelEn: "Italy" },
  { value: "jamaique", label: "Jamaïque", labelEn: "Jamaica" },
  { value: "japon", label: "Japon", labelEn: "Japan" },
  { value: "jordanie", label: "Jordanie", labelEn: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan", labelEn: "Kazakhstan" },
  { value: "kenya", label: "Kenya", labelEn: "Kenya" },
  { value: "kirghizistan", label: "Kirghizistan", labelEn: "Kyrgyzstan" },
  { value: "kiribati", label: "Kiribati", labelEn: "Kiribati" },
  { value: "koweit", label: "Koweït", labelEn: "Kuwait" },
  { value: "laos", label: "Laos", labelEn: "Laos" },
  { value: "lesotho", label: "Lesotho", labelEn: "Lesotho" },
  { value: "lettonie", label: "Lettonie", labelEn: "Latvia" },
  { value: "liban", label: "Liban", labelEn: "Lebanon" },
  { value: "liberia", label: "Liberia", labelEn: "Liberia" },
  { value: "libye", label: "Libye", labelEn: "Libya" },
  { value: "liechtenstein", label: "Liechtenstein", labelEn: "Liechtenstein" },
  { value: "lituanie", label: "Lituanie", labelEn: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg", labelEn: "Luxembourg" },
  { value: "macedoine", label: "Macédoine", labelEn: "North Macedonia" },
  { value: "madagascar", label: "Madagascar", labelEn: "Madagascar" },
  { value: "malaisie", label: "Malaisie", labelEn: "Malaysia" },
  { value: "malawi", label: "Malawi", labelEn: "Malawi" },
  { value: "maldives", label: "Maldives", labelEn: "Maldives" },
  { value: "mali", label: "Mali", labelEn: "Mali" },
  { value: "malte", label: "Malte", labelEn: "Malta" },
  { value: "maroc", label: "Maroc", labelEn: "Morocco" },
  { value: "marshall", label: "Marshall", labelEn: "Marshall Islands" },
  { value: "maurice", label: "Maurice", labelEn: "Mauritius" },
  { value: "mauritanie", label: "Mauritanie", labelEn: "Mauritania" },
  { value: "mexique", label: "Mexique", labelEn: "Mexico" },
  { value: "micronesie", label: "Micronésie", labelEn: "Micronesia" },
  { value: "moldavie", label: "Moldavie", labelEn: "Moldova" },
  { value: "monaco", label: "Monaco", labelEn: "Monaco" },
  { value: "mongolie", label: "Mongolie", labelEn: "Mongolia" },
  { value: "montenegro", label: "Monténégro", labelEn: "Montenegro" },
  { value: "mozambique", label: "Mozambique", labelEn: "Mozambique" },
  { value: "namibie", label: "Namibie", labelEn: "Namibia" },
  { value: "nauru", label: "Nauru", labelEn: "Nauru" },
  { value: "nepal", label: "Népal", labelEn: "Nepal" },
  { value: "nicaragua", label: "Nicaragua", labelEn: "Nicaragua" },
  { value: "niger", label: "Niger", labelEn: "Niger" },
  { value: "nigeria", label: "Nigeria", labelEn: "Nigeria" },
  { value: "norvege", label: "Norvège", labelEn: "Norway" },
  { value: "nouvelle-zelande", label: "Nouvelle-Zélande", labelEn: "New Zealand" },
  { value: "oman", label: "Oman", labelEn: "Oman" },
  { value: "ouganda", label: "Ouganda", labelEn: "Uganda" },
  { value: "ouzbekistan", label: "Ouzbékistan", labelEn: "Uzbekistan" },
  { value: "pakistan", label: "Pakistan", labelEn: "Pakistan" },
  { value: "palaos", label: "Palaos", labelEn: "Palau" },
  { value: "panama", label: "Panama", labelEn: "Panama" },
  { value: "papouasie-nouvelle-guinee", label: "Papouasie-Nouvelle-Guinée", labelEn: "Papua New Guinea" },
  { value: "paraguay", label: "Paraguay", labelEn: "Paraguay" },
  { value: "pays-bas", label: "Pays-Bas", labelEn: "Netherlands" },
  { value: "perou", label: "Pérou", labelEn: "Peru" },
  { value: "philippines", label: "Philippines", labelEn: "Philippines" },
  { value: "pologne", label: "Pologne", labelEn: "Poland" },
  { value: "portugal", label: "Portugal", labelEn: "Portugal" },
  { value: "qatar", label: "Qatar", labelEn: "Qatar" },
  { value: "republique-dominicaine", label: "République dominicaine", labelEn: "Dominican Republic" },
  { value: "republique-tcheque", label: "République tchèque", labelEn: "Czech Republic" },
  { value: "roumanie", label: "Roumanie", labelEn: "Romania" },
  { value: "royaume-uni", label: "Royaume-Uni", labelEn: "United Kingdom" },
  { value: "russie", label: "Russie", labelEn: "Russia" },
  { value: "rwanda", label: "Rwanda", labelEn: "Rwanda" },
  { value: "saint-christophe-et-nieves", label: "Saint-Christophe-et-Niévès", labelEn: "Saint Kitts and Nevis" },
  { value: "saint-marin", label: "Saint-Marin", labelEn: "San Marino" },
  { value: "saint-vincent-et-les-grenadines", label: "Saint-Vincent-et-les-Grenadines", labelEn: "Saint Vincent and the Grenadines" },
  { value: "sainte-lucie", label: "Sainte-Lucie", labelEn: "Saint Lucia" },
  { value: "salomon", label: "Salomon", labelEn: "Solomon Islands" },
  { value: "salvador", label: "Salvador", labelEn: "El Salvador" },
  { value: "samoa", label: "Samoa", labelEn: "Samoa" },
  { value: "sao-tome-et-principe", label: "Sao Tomé-et-Principe", labelEn: "Sao Tome and Principe" },
  { value: "senegal", label: "Sénégal", labelEn: "Senegal" },
  { value: "serbie", label: "Serbie", labelEn: "Serbia" },
  { value: "seychelles", label: "Seychelles", labelEn: "Seychelles" },
  { value: "sierra-leone", label: "Sierra Leone", labelEn: "Sierra Leone" },
  { value: "singapour", label: "Singapour", labelEn: "Singapore" },
  { value: "slovaquie", label: "Slovaquie", labelEn: "Slovakia" },
  { value: "slovenie", label: "Slovénie", labelEn: "Slovenia" },
  { value: "somalie", label: "Somalie", labelEn: "Somalia" },
  { value: "soudan", label: "Soudan", labelEn: "Sudan" },
  { value: "soudan-du-sud", label: "Soudan du Sud", labelEn: "South Sudan" },
  { value: "sri-lanka", label: "Sri Lanka", labelEn: "Sri Lanka" },
  { value: "suede", label: "Suède", labelEn: "Sweden" },
  { value: "suisse", label: "Suisse", labelEn: "Switzerland" },
  { value: "suriname", label: "Suriname", labelEn: "Suriname" },
  { value: "swaziland", label: "Swaziland", labelEn: "Swaziland" },
  { value: "syrie", label: "Syrie", labelEn: "Syria" },
  { value: "tadjikistan", label: "Tadjikistan", labelEn: "Tajikistan" },
  { value: "tanzanie", label: "Tanzanie", labelEn: "Tanzania" },
  { value: "tchad", label: "Tchad", labelEn: "Chad" },
  { value: "thailande", label: "Thaïlande", labelEn: "Thailand" },
  { value: "timor-oriental", label: "Timor oriental", labelEn: "East Timor" },
  { value: "togo", label: "Togo", labelEn: "Togo" },
  { value: "tonga", label: "Tonga", labelEn: "Tonga" },
  { value: "trinite-et-tobago", label: "Trinité-et-Tobago", labelEn: "Trinidad and Tobago" },
  { value: "tunisie", label: "Tunisie", labelEn: "Tunisia" },
  { value: "turkmenistan", label: "Turkménistan", labelEn: "Turkmenistan" },
  { value: "turquie", label: "Turquie", labelEn: "Turkey" },
  { value: "tuvalu", label: "Tuvalu", labelEn: "Tuvalu" },
  { value: "ukraine", label: "Ukraine", labelEn: "Ukraine" },
  { value: "uruguay", label: "Uruguay", labelEn: "Uruguay" },
  { value: "vanuatu", label: "Vanuatu", labelEn: "Vanuatu" },
  { value: "vatican", label: "Vatican", labelEn: "Vatican City" },
  { value: "venezuela", label: "Venezuela", labelEn: "Venezuela" },
  { value: "vietnam", label: "Viêt Nam", labelEn: "Vietnam" },
  { value: "yemen", label: "Yémen", labelEn: "Yemen" },
  { value: "zambie", label: "Zambie", labelEn: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe", labelEn: "Zimbabwe" },
]